### ISSUE TITLE
User can look through photos

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/ajax-project#1]
## ⚙️ Feature
User can click the left and right buttons to look at photos from the api
## 📐 Functionality

Users will start off on this screen, and will be able to look through photos

## 🖼️ Wireframes

<img width="188" alt="Screen Shot 2021-07-27 at 10 16 24 AM" src="https://user-images.githubusercontent.com/85326339/127198757-2628bb9d-f71c-406b-aa35-caf0056b000a.png">
<img width="398" alt="Screen Shot 2021-07-27 at 10 16 14 AM" src="https://user-images.githubusercontent.com/85326339/127198764-34dbb8fc-d85a-4cd9-bf82-407e0c0fe1a1.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a header to the html with the Photo Rater name
- [x] Set background color
- [x] Add a place holder image
- [x] Add left and right buttons
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Add photos from the api
- [x] Allow the user to look through photos using left and right buttons
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
