### ISSUE TITLE
User can rate photo

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/ajax-project#3]
## ⚙️ Feature
Users will be able to press the rate icon which will open a modal for them to leave a rating out of five stars.
## 📐 Functionality
Press the icon, submit a rating, or close the modal without leaving a rating.
## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="641" alt="Screen Shot 2021-07-28 at 12 49 51 PM" src="https://user-images.githubusercontent.com/85326339/127386715-cc50512b-0fc9-42dc-8b27-63b184cbc9cf.png">
<img width="641" alt="Screen Shot 2021-07-28 at 12 50 18 PM" src="https://user-images.githubusercontent.com/85326339/127386728-7d9903b4-2a89-4809-b306-bd857a4b5ef3.png">
<img width="213" alt="Screen Shot 2021-07-28 at 12 50 29 PM" src="https://user-images.githubusercontent.com/85326339/127386737-890c95a3-bcd2-4fe7-846c-80ea72ee09d8.png">
<img width="211" alt="Screen Shot 2021-07-28 at 12 50 36 PM" src="https://user-images.githubusercontent.com/85326339/127386756-f0f696f7-6dcb-4cd4-a3d6-8c936bc3208b.png">

## ✅ Task List

- [x] Add rating button to html
- [x] Add an event listener to the star button
- [x] Add a hidden class to css
- [x] Create the modal
- [x] Create function that removes hidden class from modal when rating button is clicked
- [x] Allow user to rate the image
- [x] Add the rating along with the image rated to the local storage
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
