### ISSUE TITLE
User can write a review on a photo.

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/ajax-project#5]
## ⚙️ Feature
Users will be able to write a review on a photo
## 📐 Functionality
User presses the icon with the pen and paper, the review modal opens, they can either submit a review or press cancel and go back to the main page.
## 🖼️ Wireframes

<img width="188" alt="Screen Shot 2021-07-30 at 10 21 07 AM" src="https://user-images.githubusercontent.com/85326339/127689364-71def3c7-b313-44cb-973d-c6ddcff7872e.png">
<img width="189" alt="Screen Shot 2021-07-30 at 10 21 22 AM" src="https://user-images.githubusercontent.com/85326339/127689370-3457bc2c-5fc2-45ef-bcf0-634ba6eed5b9.png">
<img width="345" alt="Screen Shot 2021-07-30 at 10 21 32 AM" src="https://user-images.githubusercontent.com/85326339/127689373-20fd4eed-195c-4b6e-8545-b8880fa1fc08.png">
<img width="346" alt="Screen Shot 2021-07-30 at 10 21 38 AM" src="https://user-images.githubusercontent.com/85326339/127689378-fc85baa4-07fc-4a22-9798-01152bf703cf.png">

## ✅ Task List

- [x] Add the button for writing a review
- [x] Add the form to the html
- [x] Add an event listener to the button for opening the form
- [x] Make use of previous function for submitting or closing the button
- [x] Store the form to the data model and local storage
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
