### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/ajax-project#7]
## ⚙️ Feature
Users will be able to view their profile

## 📐 Functionality
Users will be able to press the profile icon on the top right which will bring them to a view of their profile. From there they can switch back to the images by pressing the image icon on the top right.

## 🖼️ Wireframes

<img width="127" alt="Screen Shot 2021-07-30 at 1 18 55 PM" src="https://user-images.githubusercontent.com/85326339/127713661-a28d9742-7b27-4985-b2d1-e97fb4adf523.png">
<img width="268" alt="Screen Shot 2021-07-30 at 1 19 02 PM" src="https://user-images.githubusercontent.com/85326339/127713665-70baf4ba-ecd7-4c53-8f7b-99ae59c9d12e.png">
<img width="453" alt="Screen Shot 2021-07-30 at 1 19 31 PM" src="https://user-images.githubusercontent.com/85326339/127713667-16ebc5fd-cc40-4142-a50c-60d3eed78fc3.png">
<img width="450" alt="Screen Shot 2021-07-30 at 1 19 35 PM" src="https://user-images.githubusercontent.com/85326339/127713668-57cb8af4-9798-4b42-a12f-14dc8e02f251.png">
<img width="267" alt="Screen Shot 2021-07-30 at 1 19 09 PM" src="https://user-images.githubusercontent.com/85326339/127713670-6a1ba3b2-982f-457b-8000-58d74b7d484a.png">
<img width="266" alt="Screen Shot 2021-07-30 at 1 19 14 PM" src="https://user-images.githubusercontent.com/85326339/127713672-b3b6c358-da82-43e2-907d-8a7172b4dad4.png">
<img width="562" alt="Screen Shot 2021-07-30 at 1 19 23 PM" src="https://user-images.githubusercontent.com/85326339/127713674-cc458445-9d12-42e1-a55c-40e9ac759598.png">
<img width="308" alt="Screen Shot 2021-08-04 at 5 01 24 PM" src="https://user-images.githubusercontent.com/85326339/128270675-f6bc9c38-7bc4-4e7d-865e-e26962fd795d.png">
<img width="918" alt="Screen Shot 2021-08-04 at 5 00 51 PM" src="https://user-images.githubusercontent.com/85326339/128270680-03ac5493-798f-4025-bfe1-0a36d1e12598.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add profile icon to the top right
- [x] Add an event listener for a click event on profile icon
- [x] Create a function that handles the view changes
- [x] Create drop down menu for Ratings and Reviews
- [x] If there are no ratings and reviews display the text from the figma
- [ ] Create a dom tree for displaying the entries
- [ ] Add styling to the dom tree to match the figma
- [ ] Create an empty UL element to append ratings and reviews
- [ ] If there are entries display them on the selected view
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
